export { default as wxConfig } from './wxConfig'
export { default as wxSave } from './wxSave'
export { default as wxLocation } from './wxLocation'
export { default as wxShare } from './wxShare'
export { default as wxPay } from './wxPay'
export { default as wxHide } from './wxHide'
