
// import './global/slide'
import './global/fade'
import './global/zoom-in'
import './global/icon'
import './global/custom'

export * from './mixins/hairline'
export { default as placeholder } from './mixins/placeholder'
export { default as ellipsis } from './mixins/ellipsis'

export { default as withTheme } from './withTheme'
export { default as createTheme } from './createTheme'
export { default as withStyles } from './withStyles'
export { default as withPropsState } from './withPropsState'
export { ThemeProvider } from 'vue-styled-components'
export { default as zIndex } from './zIndex'
export { default as StyledComponent } from './styledComponent'
export { default as TypedComponent } from './typedComponent'
export { default as DescribedComponent } from './describedComponent'
